### ISSUE TITLE
where to find the sample "bad_pod_name"

### ISSUE THREAD

**Issue by bjin01** [kubewarden/rust-policy-template#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

apiVersion: v1
kind: Pod
metadata:
  name: bad_name1
spec:
  containers:
    - name: nginx
      image: nginx:latest

### Expected Behavior

Where can I find the source code in rust for this example mentioned in https://docs.kubewarden.io/writing-policies/rust/02-create-policy.html

In this repo and folder kubewarden/rust-policy-template I don't see the codes for this "bad pod name".

Greetings from Bo Jin (SUSE)

### Steps To Reproduce

Not an issue yet

**Comment by ereslibre** [comment]
The documentation on https://docs.kubewarden.io/writing-policies/rust/02-create-policy.html is about creating a policy of your own that rejects pods by name.

It is not a real policy that exists, is part of the book as a way to explain how you can write your own policy.

It goes through the sections of the book:
- https://docs.kubewarden.io/writing-policies/rust/02-create-policy.html
- https://docs.kubewarden.io/writing-policies/rust/03-define-policy-settings.html
- https://docs.kubewarden.io/writing-policies/rust/04-write-validation-logic.html
- https://docs.kubewarden.io/writing-policies/rust/05-mutation-policy.html
- https://docs.kubewarden.io/writing-policies/rust/06-logging.html
- https://docs.kubewarden.io/writing-policies/rust/07-build-and-distribute.html
